#!/bin/bash

function ExtractDeleteQueryDetails() {
    # Example DELETE query
    query="DELETE FROM Employees WHERE Name = Omar AND Department = HR AND Salary = 50000"
    # Regex to extract table name and conditions
    regex="^DELETE[[:space:]]+FROM[[:space:]]+([a-zA-Z_][a-zA-Z0-9_]*)[[:space:]]+WHERE[[:space:]]+(.+)$"

    # Validate and extract table name and conditions

    
    if [[ $query =~ $regex ]]; then
        table_name="${BASH_REMATCH[1]}"
        conditions="${BASH_REMATCH[2]}"
    else
        echo "Invalid DELETE query syntax."
        exit 1
    fi

    echo "Table Name: $table_name"

    # columnss=$(echo "$conditions" | awk -F'=' '{print $3}' | xargs)
    # echo "colllllllllllllmns $columnss" 
    
    # Extract the column-value pairs from the conditions
    IFS='AND' read -r -a condition_array <<< "$conditions"

    echo "Conditions:"
    valuess=""
    for condition in "${condition_array[@]}"; do
        # Trim spaces around the condition
        condition=$(echo "$condition" | xargs)

        # Extract column name and value
        if [[ $condition =~ ^([a-zA-Z_][a-zA-Z0-9_]*)[[:space:]]*=[[:space:]]*(.+)$ ]]; then
            column="${BASH_REMATCH[1]}"
            value="${BASH_REMATCH[2]}"
            echo "colllllllll $column"
            echo "valllllllllll $value"
            # Remove quotes from string values
            value=$(echo "$value" | sed "s/^'//;s/'$//")
            valuess+="$value "
            echo " $value"
        # else
            # echo "Invalid condition: $condition"
        fi
    done

    echo "valesssssssssssssss$valuess"

    pattern=$(echo "$valuess" | sed 's/ /.*, /g')
    pattern=$(echo "$pattern" | sed 's/, $//')
    echo "patterrrrrrrrrrrrn $pattern"
    sed -i "/$pattern/d" "$table_name" &&
      echo "Query executed SUCCESSFULLY" &&
     return 0;
}

ExtractDeleteQueryDetails
